#This is meant to be a call and response where the request is a queary bool and the response is a list of stamped points

#Query bool, (place holder)
bool query
---
#The response is associated with a time stamp, a frame, and a seq #.
geometry_msgs/PolygonStamped ptList
